// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzqthnwMtIGNisTm9scqYrUTtZeSmrEM8',
    appId: '1:1062481440286:android:6e6c6ab62ebe692161c80f',
    messagingSenderId: '1062481440286',
    projectId: 'pbl6-goship',
    databaseURL: 'https://pbl6-goship-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbl6-goship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2jLWtqj8yf0ZUCGFsS1Ho-9dpsJIQ0k',
    appId: '1:1062481440286:ios:64b7bfbb30d847ee61c80f',
    messagingSenderId: '1062481440286',
    projectId: 'pbl6-goship',
    databaseURL: 'https://pbl6-goship-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pbl6-goship.appspot.com',
    iosClientId: '1062481440286-4n7iifi1enahgrsku39uig1i30lch1au.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoShipPbl6',
  );
}
